using System;
using UnityEngine;

namespace Kaninbanker
{
    /// <summary>
    /// Runtime catalog generated by the editor from imported 2D project assets.
    /// Asset Store/source files stay where their license/import process places them;
    /// this catalog stores Unity references and lets gameplay prefer imported art/audio
    /// while retaining procedural fallbacks when a category is empty.
    /// </summary>
    public sealed class Kaninbanker2DAssetCatalog : ScriptableObject
    {
        public const string ResourcesPath = "Kaninbanker/Generated/Kaninbanker2DAssetCatalog";

        [Header("Rabbit sprites")]
        public Sprite[] normalRabbits = Array.Empty<Sprite>();
        public Sprite[] fastRabbits = Array.Empty<Sprite>();
        public Sprite[] goldRabbits = Array.Empty<Sprite>();
        public Sprite[] armoredRabbits = Array.Empty<Sprite>();
        public Sprite[] bombRabbits = Array.Empty<Sprite>();
        public Sprite[] bossRabbits = Array.Empty<Sprite>();

        [Header("World and UI sprites")]
        public Sprite[] holes = Array.Empty<Sprite>();
        public Sprite[] backgrounds = Array.Empty<Sprite>();
        public Sprite[] foregrounds = Array.Empty<Sprite>();
        public Sprite[] effects = Array.Empty<Sprite>();
        public Sprite[] ui = Array.Empty<Sprite>();
        public Sprite[] hammers = Array.Empty<Sprite>();
        public Sprite[] genericSprites = Array.Empty<Sprite>();

        [Header("Audio")]
        public AudioClip[] hit = Array.Empty<AudioClip>();
        public AudioClip[] combo = Array.Empty<AudioClip>();
        public AudioClip[] miss = Array.Empty<AudioClip>();
        public AudioClip[] rabbitPop = Array.Empty<AudioClip>();
        public AudioClip[] roundStart = Array.Empty<AudioClip>();
        public AudioClip[] gameOver = Array.Empty<AudioClip>();
        public AudioClip[] uiAudio = Array.Empty<AudioClip>();
        public AudioClip[] power = Array.Empty<AudioClip>();
        public AudioClip[] bomb = Array.Empty<AudioClip>();
        public AudioClip[] boss = Array.Empty<AudioClip>();
        public AudioClip[] reward = Array.Empty<AudioClip>();
        public AudioClip[] music = Array.Empty<AudioClip>();
        public AudioClip[] genericAudio = Array.Empty<AudioClip>();

        private static Kaninbanker2DAssetCatalog cached;

        public static Kaninbanker2DAssetCatalog Load()
        {
            if (cached == null)
                cached = Resources.Load<Kaninbanker2DAssetCatalog>(ResourcesPath);
            return cached;
        }

        internal static void ClearRuntimeCache()
        {
            cached = null;
        }

        internal Sprite PickRabbit(RabbitKind2D kind, int seed)
        {
            switch (kind)
            {
                case RabbitKind2D.Fast: return Pick(fastRabbits, seed) ?? Pick(normalRabbits, seed);
                case RabbitKind2D.Gold: return Pick(goldRabbits, seed) ?? Pick(normalRabbits, seed);
                case RabbitKind2D.Armored: return Pick(armoredRabbits, seed) ?? Pick(normalRabbits, seed);
                case RabbitKind2D.Bomb: return Pick(bombRabbits, seed) ?? Pick(normalRabbits, seed);
                case RabbitKind2D.Boss: return Pick(bossRabbits, seed) ?? Pick(normalRabbits, seed);
                default: return Pick(normalRabbits, seed);
            }
        }

        public Sprite PickHole(int seed) => Pick(holes, seed);
        public Sprite PickBackground(int seed) => Pick(backgrounds, seed);
        public Sprite PickForeground(int seed) => Pick(foregrounds, seed);
        public Sprite PickEffect(int seed) => Pick(effects, seed);
        public Sprite PickUi(int seed) => Pick(ui, seed);
        public Sprite PickHammer(int seed) => Pick(hammers, seed);

        public AudioClip PickHit(int seed) => Pick(hit, seed);
        public AudioClip PickCombo(int seed) => Pick(combo, seed);
        public AudioClip PickMiss(int seed) => Pick(miss, seed);
        public AudioClip PickRabbitPop(int seed) => Pick(rabbitPop, seed);
        public AudioClip PickRoundStart(int seed) => Pick(roundStart, seed);
        public AudioClip PickGameOver(int seed) => Pick(gameOver, seed);
        public AudioClip PickUiAudio(int seed) => Pick(uiAudio, seed);
        public AudioClip PickPower(int seed) => Pick(power, seed);
        public AudioClip PickBomb(int seed) => Pick(bomb, seed);
        public AudioClip PickBoss(int seed) => Pick(boss, seed);
        public AudioClip PickReward(int seed) => Pick(reward, seed);
        public AudioClip PickMusic(int seed) => Pick(music, seed);

        private static T Pick<T>(T[] items, int seed) where T : UnityEngine.Object
        {
            if (items == null || items.Length == 0)
                return null;
            int index = Mathf.Abs(seed == int.MinValue ? 0 : seed) % items.Length;
            return items[index];
        }
    }
}
